package com.k00ntz.aoc2020.utils

import Day1


fun main(){
    println("Day 1")
    Day1().run()
//    println("Day 2")
//    Day2().run()
//    println("Day 3")
//    Day3().run()
//    println("Day 4")
//    Day4().run()
//    println("Day 5")
//    Day5().run()
//    println("Day 6")
//    Day6().run()
//    println("Day 7")
//    Day7().run()
//    println("Day 8")
//    Day8().run()
//    println("Day 9")
//    Day9().run()
//    println("Day 10")
//    Day10().run()
//    println("Day 11")
//    Day11().run()
//    println("Day 12")
//    Day12().run()
//    println("Day 13")
//    Day13().run()
//    println("Day 14")
//    Day14().run()
//    println("Day 15")
//    Day15().run()
//    println("Day 16")
//    Day16().run()
//    println("Day 17")
//    Day17().run()
}